### ISSUE TITLE
Using google trends or random word lists

### ISSUE THREAD

**Issue by udithap** [mikeyaworski/Automated-Bing-Searches#11]
Instead of using a predefined list which will result in similar search patterns over a length of time among many concurrent users, will it be possible to use google trends API (https://trends.google.com/trends/api/dailytrends?hl=en-US&ed={}&geo=US&ns=15) or random word lists (eg: https://www.randomlists.com/data/words.json)?

**Comment by mikeyaworski** [comment]
I don't think a random words list would be great since the search queries would be nonsensical and obviously bot-generated. The current approach is better since we can just add more words and many more query templates to get more variety.

Using the Google Trends API is something that I can look into. The link you posted is a 400 though.

And I'm open to PR's on both adding more words/query templates or integrating a public Google Trends API (if one exists).

**Comment by udithap** [comment]
Here is the correct link,(hl=en-US&ed=20200725) should be replaced with the current date YYYYMMDD.
https://trends.google.com/trends/api/dailytrends?hl=en-US&ed=20200725&geo=US&ns=15

**Comment by mikeyaworski** [comment]
Yeah the problem with having a non-public API is that you'll run into CORS issues. Since the endpoint is not intended for public use, we don't get the response header we need to allow CORS. For example, making a network request to Google from this extension results in something like:

> Access to fetch at 'https://trends.google.com/trends/api/dailytrends?hl=en-US&ed=20200725&geo=US&ns=15' from origin 'chrome-extension://nakahpganddgclfmpeckfibnolncbhen' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

To get around this, we'll need to hit a proxy service which allows CORS and the proxy service will need to hit this Google endpoint itself. We could use `https://cors-anywhere.herokuapp.com/` and fallback to the current search query approach if this request fails for some reason (maybe the service is down, or google changed their endpoint, etc.).

Example which works:

```
fetch('https://cors-anywhere.herokuapp.com/' + 'https://trends.google.com/trends/api/dailytrends?hl=en-US&tz=240&geo=US&ns=15')
  .then(r => {
    r.text().then(console.log)
  })
  .catch(console.log);
```
