### ISSUE TITLE
Keyboard Shortcut to run Automated Bing Searches with last saved options

### ISSUE THREAD

**Issue by udithap** [mikeyaworski/Automated-Bing-Searches#15]
Please consider adding an option for a keyboard shortcut to run the searches with a keyboard shortcut. I can set a keyboard shortcut to open A-B-S using chrome options, but it requires me to manually click on Search button once open.

I am actually thinking of an Autohotkey script that allows me to log in to bing with more than one account and run A-B-S automatically, but I have been unable to get it to interact with A-B-S to click on the Search button. A keyboard shortcut will sort this problem, as well as being useful for others to run the searches as quickly as possible.

**Comment by mikeyaworski** [comment]
Sure, this is a pretty simple thing to do. I'll get to this in a few days.

**Comment by udithap** [comment]
Yes, a hotkey was what I had in mind. There is no need for a UI option. Thanks.

**Comment by mikeyaworski** [comment]
@udithap The hotkey is Ctrl+Shift+S and version 1.2.14 will have this implemented. It's publishing now.

**Comment by udithap** [comment]
For some reason, the hotkey is not working on Firefox. For some reason even the shortcut key that is used to open the UI in chrome, does not work on firefox.

**Comment by mikeyaworski** [comment]
It works for me on Firefox. What version of Firefox are you running? I believe it's possible to have conflicting hotkeys if you have some custom settings on the browser as well.

**Comment by udithap** [comment]
Tried Firefox 80.0.1 (64bit) on Windows 10, and Firefox 80.0.1 (32bit) on Windows 7.
Firefox will prevent using conflicting shortcuts. So, I do not think it is the issue.

[cid:989cea00-6ca9-482b-a2ca-455c2e6fa8d5]

________________________________

**Comment by mikeyaworski** [comment]
Okay I was able to reproduce this just now. This looks like a bug with the latest production version of Firefox. I didn't run into it myself previously since I use the Beta version of Firefox.

The hotkey won't work since it `Ctrl+Shift+S ` invokes the screenshot tool and therefore does not dispatch the command to the extension. Hopefully this will be fixed in the next production build of Firefox, but for now, I fixed it by going to `about:config` and flipping the values for `extensions.screenshots.disabled` and `extensions.screenshots.upload-disabled`. The hotkey was then working and even after flipping the values back to their original values, the hotkey continued to work. So it definitely seems like a bug which can be avoided by just changing a value back and forth.

Let me know if it does or doesn't work for you. I can look into it more if it doesn't.
